#include QMK_KEYBOARD_H

#define L1_RGUI LM(1, MOD_RGUI)

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = default(KC_GESC,KC_Q,KC_W,KC_E,KC_R,KC_T,KC_Y,KC_U,KC_I,KC_O,KC_P,KC_BSPC,KC_LCTL,KC_A,KC_S,KC_D,KC_F,KC_G,KC_H,KC_J,KC_K,KC_L,KC_ENT,KC_LSFT,KC_Z,KC_X,KC_C,KC_V,KC_B,KC_N,KC_M,KC_COMM,RSFT_T(KC_DOT),RSFT_T(KC_SLSH),LT(3,KC_LCTL),LT(3,KC_LGUI),KC_LALT,LT(1,KC_SPC),LT(2,KC_SPC),KC_RALT,RGUI_T(KC_APP),KC_RCTL),
	[1] = default(KC_NO,KC_F9,KC_F10,KC_F11,KC_F12,KC_NO,KC_NO,KC_NO,KC_LBRC,KC_RBRC,KC_BSLS,KC_DEL,KC_TAB,KC_F5,KC_F6,KC_F7,KC_F8,KC_NO,KC_NO,KC_NO,KC_SCLN,KC_QUOT,KC_TRNS,KC_LSFT,KC_F1,KC_F2,KC_F3,KC_F4,KC_NO,KC_NO,KC_NO,KC_NO,KC_RSFT,KC_RSFT,KC_LCTL,KC_NO,KC_TRNS,KC_TRNS,KC_RSFT,KC_RALT,KC_RGUI,KC_RCTL),
	[2] = default(KC_GRV,KC_NO,KC_7,KC_8,KC_9,KC_0,KC_NO,KC_NO,KC_UP,KC_NO,KC_NO,KC_DEL,KC_TAB,KC_NO,KC_4,KC_5,KC_6,KC_MINS,KC_NO,KC_LEFT,KC_DOWN,KC_RGHT,KC_TRNS,KC_LSFT,KC_NO,KC_1,KC_2,KC_3,KC_EQL,KC_NO,KC_NO,KC_NO,KC_RSFT,KC_NO,KC_LCTL,KC_NO,KC_TRNS,KC_LSFT,KC_TRNS,KC_TRNS,KC_TRNS,KC_RCTL),
	[3] = default(RESET,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,LCTL(KC_Y),KC_NO,KC_PGUP,KC_NO,KC_NO,KC_DEL,LGUI(KC_TAB),LCTL(KC_A),LCTL(KC_S),LCTL(KC_D),LCTL(KC_F),KC_NO,KC_NO,KC_HOME,KC_PGDN,KC_END,KC_TRNS,C_S_T(KC_NO),LCTL(KC_Z),LCTL(KC_X),LCTL(KC_C),LCTL(KC_V),KC_NO,KC_NO,KC_NO,KC_NO,C_S_T(KC_NO),KC_NO,KC_NO,KC_LGUI,LCA_T(KC_NO),RCTL(KC_SPC),RCTL(KC_SPC),KC_RALT,KC_NO,KC_RCTL)
};
